# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
