# Generated by Django 2.0.1 on 2018-01-09 23:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
