# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_posts_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title2',
        ),
    ]
