# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180110_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='instrument',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
        migrations.AddField(
            model_name='musician',
            name='context',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(null=True, upload_to='postsImages'),
        ),
        migrations.AddField(
            model_name='musician',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='updatedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
