# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 12:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180113_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('context', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='postsImages')),
                ('createdDate', models.DateField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
