# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180124_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updatedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
