# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180124_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
