# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180124_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
    ]
